### ISSUE TITLE
Missing runtime dependencies for gd and mcrypt

### ISSUE THREAD

**Issue by punkstar** [meanbee/docker-magento#1]
When running command line php on the 5.6-apache tag I get the following warnings:

```
$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/gd.so' - libjpeg.so.62: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/mcrypt.so' - libmcrypt.so.4: cannot open shared object file: No such file or directory in Unknown on line 0
PHP 5.6.14 (cli) (built: Oct 23 2015 21:01:59)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

When checking `phpinfo` through apache I see references to the gd and mcrypt ini files being picked up, but no reference to the libraries in the `phpinfo` output.

**Comment by punkstar** [comment]
After copying the Dockerfile locally, removing the following line fixed the warnings for me:

```
apt-get purge --auto-remove -y $build_packages
```

We'll still need to do a clean up after the package installs to keep the image size down.  The fix is likely just a tweak to this command.

**Comment by punkstar** [comment]
Opened #2, but leaving this issue here as we need to clean up.

**Comment by punkstar** [comment]
I use the following approach on my other projects which seems to do the trick:

```
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

I'm in favour of just doing that to close this issue down?

**Comment by tgerulaitis** [comment]
Saves me the pain of having to figure out which dependencies are build only, so I'm all for that :+1:
