### ISSUE TITLE
Add intl and zip extensions to run magento 2.1

### ISSUE THREAD

**Issue by marceloaguero** [meanbee/docker-magento#43]
I'm using your docker images to run magento 2.1 community edition. This new version requires intl and zip php extensions.

If you like, you can add those extensions to your Dockerfiles:

```
RUN build_packages=" ... libicu-dev"
...
    && docker-php-ext-install intl \
    && docker-php-ext-install zip \
...
```

And that's it.

Regards

**Comment by tgerulaitis** [comment]
Thanks for that. The images are not really aimed at running Magento 2 (we run our Magento 2 installations with https://github.com/meanbee/docker-magento2), but if it's just the two PHP extensions that are missing, I don't see any reason against adding them!
