### ISSUE TITLE
Can not make cron work

### ISSUE THREAD

**Issue by gety9** [meanbee/docker-magento#59]
Guys,

It's more a question than an issue, could you please explain how to run cron here?

I am using your default [docker-compose.yml](https://github.com/meanbee/docker-magento/blob/master/docker-compose.yml) 

Everything works fine, except cron.

Do i need to set it up?

I've tried:
```
docker exec -ti cpd3_web_1 sh
# crontab -l
sh: 1: crontab: not found
```

And
```
$ docker exec -ti cpd3_cron_1 sh
# crontab -l
no crontab for root
# crontab -e
no crontab for root - using an empty one
/usr/bin/sensible-editor: 25: /usr/bin/sensible-editor: editor: not found
/usr/bin/sensible-editor: 28: /usr/bin/sensible-editor: nano: not found
/usr/bin/sensible-editor: 31: /usr/bin/sensible-editor: nano-tiny: not found
/usr/bin/sensible-editor: 34: /usr/bin/sensible-editor: vi: not found
Couldn't find an editor!
Set the $EDITOR environment variable to your desired editor.
crontab: "/usr/bin/sensible-editor" exited with status 1
```

**Comment by bobbyshaw** [comment]
Just seen your post on reddit too and responded there: https://www.reddit.com/r/Magento/comments/7uw5p0/help_with_cron_docker_container/

It'd be good to get confirmation on why you think that (the magento ) cron isn't running.

**Comment by punkstar** [comment]
Hey @gety9. Can I get an update on whether you're still experiencing an issue or not? I don't believe we've run into cron issues running these images internally.

**Comment by gety9** [comment]
Guys, thank you for your help!

As you advised the issue was that working_dir was not working correctly. When i manually changed it in /etc/cron.d/magento it worked, but i had to redo it on each stop/start of the container.

Than i tried to remove all the images from my machine (rmi), and run the same docker-compose.yml again - it fixed everything.

Right now the paths are correct.

Thank you for taking your time and replying, you guys are amazing!

**Comment by gety9** [comment]
Fixed, was dos formatting issue on my end.
