### ISSUE TITLE
Correct way to start n98-magerun

### ISSUE THREAD

**Issue by gety9** [meanbee/docker-magento#62]
Guys hi,

What's the correct way to start n98-magerun with these images?

Now i am using it like this:

`$ docker exec -ti p1_cron_1 bash`

and  than

`n98-magerun.phar --version`

but it's always shows 

> It's not recommended to run n98-magerun as root user

so i guess i am using it wrong.

**Comment by tgerulaitis** [comment]
Hi @gety9,

There's a wrapper around `n98-magerun.phar` in the cli image - `magerun` - which executes Magerun as `www-data` user, so you should simply need:

```
$ docker exec -ti p1_cron_1 magerun <mageurn-command-to-run>
```

**Comment by gety9** [comment]
@tgerulaitis 

Thank you! Your suggestion is working as expected. I am closing the issue.
