### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by itsazzad** [meanbee/docker-magento#69]
This site can’t be reached
magento-dev.docker refused to connect.
Search Google for magento dev docker
ERR_CONNECTION_REFUSED

Trying with clone repo.
How to setup Magento?

**Comment by punkstar** [comment]
You need to use a proxy that supports the `VIRTUAL_HOST` environment variables, such as [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy).

**Comment by itsazzad** [comment]
@punkstar I am using WIndows 10. 
And using https://github.com/meanbee/docker-magento/blob/master/docker-compose.yml where the image is `meanbee/magento:5.6-apache`
And its saying `      - VIRTUAL_HOST=magento-dev.docker`
Am I still in need of `nginx-proxy`?

And another question was, "Where will I edit the source code of Magento?, Which folder is that in?"
Sorry if these questions are foolish.

**Comment by punkstar** [comment]
@itsazzad Yes, you'll need the nginx proxy, or you'll need to modify the `docker-compose.yml` to expose the port directly. You'll need to add the source code of Magento yourself and point the `docker-compose.yml` to it using the `appdata` service.
