### ISSUE TITLE
How to use cli image

### ISSUE THREAD

**Issue by zamoroka** [meanbee/docker-magento#73]
The `cli` container is not running, so how can I use this image to run e.g. magerun command?

**Steps to reproduce:**
1 `git clone https://github.com/meanbee/docker-magento.git`
2 `cd docker-magento`
3 `docker-compose up -d`

**Result:**
https://www.dropbox.com/s/na60nd01gshgvm8/2018-11-19_23-00-28.png?dl=0

**Env:** 
Ubuntu 16.04 
Docker version 18.09.0
docker-compose version 1.18.0

Thanks.

**Comment by eagl3s1ght** [comment]
> The `cli` container is not running, so how can I use this image to run e.g. magerun command?

I figured out that you run the CLI commands from the cron container. The CLI container only sets up (installs) all the fun stuff. Run `docker exec -it docker-magento_cron_1 bash` and then one of the cli commands like `magerun`
This could be more clear in the documentation for those not so deep into the Docker-sphere.

**Comment by punkstar** [comment]
You can use the CLI container without having to jump into the cron container, e.g.:

    docker-compose run --rm cli magerun db:console
