### ISSUE TITLE
PHP should be configured to have at least 256mb memory

### ISSUE THREAD

**Issue by punkstar** [meanbee/docker-magento#8]

**Comment by punkstar** [comment]
I think it would be wise to have a larger limit in the cli image as it's dealing with batch tasks (such as reindexing) that will probably require more than the web server.

**Comment by tgerulaitis** [comment]
Good point. I remember Magento used to recommend using 512M as the memory limit (with 256M as absolute minimum), but the official [System Requirements](http://devdocs.magento.com/guides/m1x/system-requirements.html) page no longer mentions memory.
