### ISSUE TITLE
PHP 8, Vulnerability scans, etc.

### ISSUE THREAD

**Issue by colinmollenhour** [meanbee/docker-magento#80]
I forked this project and made a handful of changes here for use in the OpenMage project:
https://github.com/meanbee/docker-magento/compare/master...colinmollenhour:docker-openmage:main

Highlights:
- Fix build errors
- Auto-build with GitHub actions on push to main
- Remove PHP <7.4
- Add PHP 8.2
- Add vulnerability scanning

I am considering proposing that my fork be moved to the openmage Github org as the official openmage container but just wanted to confirm:
- Is this project indeed no longer maintained or do you want to keep it active?
- Do you have any objection regarding licensing?

Thanks!

**Comment by bobbyshaw** [comment]
Hi @colinmollenhour, thanks for your message. I hope that you are well. 

You're correct, this is no longer maintained. I've added an MIT license for you. Feel free to use as you wish. 

Thank you 🙇‍♂️
